Algoritmo "delta"

Var
numeroa: real
numerob: real
numeroc: real
delta: real

Inicio

escreva ("Digite o A da equação de segundo grau: ")
leia (numeroa)

escreva ("Digite o B da equação de segundo grau: ")
leia (numerob)

escreva ("Digite o C da equação de segundo grau: ")
leia (numeroc)

delta <- numerob^2 - (4*numeroa*numeroc)

escreval ("O delta dessa equação é: ", delta)

Fimalgoritmo

